"""Pokemon TCG AI Battle — rule-based agent.

Kaggle simulation entry point. Must define `agent(obs: dict) -> list[int]`.

Design goals (see ../docs/ENGINE_NOTES.md for the reverse-engineered `obs` schema):
  1. Never crash and never return an illegal selection — a crash or timeout is an
     instant loss, so every code path funnels through a defensive fallback.
  2. Prefer decisions driven by the real card database (`AllCard`/`AllAttack`,
     exposed by the native engine bundled in `kaggle-environments`) over blind
     heuristics, but degrade gracefully if that database can't be loaded.
  3. Reason primarily on `option[i]["type"]` (OptionType) rather than
     `select["context"]` (SelectContext), since only a subset of context codes
     could be identified empirically — the option type is what determines which
     concrete action is being offered, in every context we observed.
"""

import ctypes
import json
import os
import re

# ---------------------------------------------------------------------------
# Card / attack database (loaded once from the native engine shipped inside
# kaggle-environments; the exact same library Kaggle runs submissions against).
# ---------------------------------------------------------------------------

CARD_DB = {}
ATTACK_DB = {}


def _load_card_db():
    global CARD_DB, ATTACK_DB
    try:
        from kaggle_environments.envs.cabt.cg.sim import lib

        lib.AllCard.restype = ctypes.c_char_p
        lib.AllAttack.restype = ctypes.c_char_p
        CARD_DB = {c["cardId"]: c for c in json.loads(lib.AllCard())}
        ATTACK_DB = {a["attackId"]: a for a in json.loads(lib.AllAttack())}
    except Exception:
        CARD_DB = {}
        ATTACK_DB = {}


_load_card_db()

# ---------------------------------------------------------------------------
# Deck loading
# ---------------------------------------------------------------------------

# `__file__` is undefined when this module's source is inlined into a Jupyter
# cell (e.g. the Kaggle Notebook mirror generated by tools/build_kaggle_kernel.py)
# rather than run as a real file, so fall back to the working directory --
# load_deck() below already tolerates deck.csv not being found there.
try:
    _HERE = os.path.dirname(os.path.abspath(__file__))
except NameError:
    _HERE = os.getcwd()
DECK_CSV_PATH = os.path.join(_HERE, "deck.csv")

# Safety net baked in directly: if deck.csv is missing/corrupted at submission
# time, we still submit a legal 60-card deck instead of instant-losing.
# Kept in sync with deck.csv (see that file for card-by-card commentary).
DEFAULT_DECK = (
    [333] * 4 + [678] * 4
    + [1086] * 4 + [1121] * 4 + [1227] * 4 + [1210] * 4 + [1205] * 4 + [1163] * 4 + [123] * 4
    + [6] * 24
)


def load_deck():
    try:
        with open(DECK_CSV_PATH, "r", encoding="utf-8") as f:
            ids = [int(line.strip()) for line in f if line.strip() and not line.strip().startswith("#")]
        if len(ids) == 60:
            return ids
    except Exception:
        pass
    return list(DEFAULT_DECK)


def _own_deck_energy_ratio():
    """Fraction of our own deck that's Basic/Special Energy. Used to
    estimate the payoff of "discard N, deal X per Energy discarded"
    attacks (see attack_score) -- computed once at import time since the
    deck doesn't change mid-match."""
    try:
        deck = load_deck()
        if not deck:
            return 0.0
        energy_count = sum(1 for cid in deck if CARD_DB.get(cid, {}).get("cardType") in (5, 6))
        return energy_count / len(deck)
    except Exception:
        return 0.0


OWN_DECK_ENERGY_RATIO = _own_deck_energy_ratio()


def _own_deck_evolution_bases():
    """Names of cards that some other card in our own deck lists as its
    `evolvesFrom` -- i.e. the specific Basic(s) that actually unlock our
    deck's evolution line(s). Computed dynamically from CARD_DB/load_deck()
    at import time rather than hardcoded to any card name, consistent with
    this project's data-driven approach (see OWN_DECK_ENERGY_RATIO above).
    Used by card_value() to distinguish "a Basic with good stats" from "the
    specific Basic this deck's plan depends on" -- verified via A/B testing
    to matter once the deck runs a second Basic species (Farfetch'd): without
    this bonus, a same-HP rival Basic ties with the evolution-enabling one in
    search/discard comparisons, diverting some search hits away from it."""
    try:
        deck = load_deck()
        names = set()
        for cid in set(deck):
            card = CARD_DB.get(cid)
            if card and card.get("evolvesFrom"):
                names.add(card["evolvesFrom"])
        return names
    except Exception:
        return set()


OWN_DECK_EVOLUTION_BASES = _own_deck_evolution_bases()


# ---------------------------------------------------------------------------
# Schema constants (see docs/ENGINE_NOTES.md)
# ---------------------------------------------------------------------------

AREA_DECK, AREA_HAND, AREA_DISCARD, AREA_INPLAY, AREA_BENCH = 1, 2, 3, 4, 5

OPT_NUMBER, OPT_YES, OPT_NO, OPT_CARD = 0, 1, 2, 3
OPT_ENERGY, OPT_PLAY, OPT_ATTACH, OPT_EVOLVE, OPT_ABILITY = 6, 7, 8, 9, 10
OPT_RETREAT, OPT_ATTACK, OPT_END = 12, 13, 14

CTX_DISCARD = 8
CTX_SETUP_ACTIVE = 1
CTX_TO_ACTIVE = 4


# ---------------------------------------------------------------------------
# Board-state helpers
# ---------------------------------------------------------------------------

def resolve_card_by_area(obs, sel, area, index, player_index=None):
    """Best-effort lookup of the static card data behind a `{area, index}` ref."""
    if area is None or index is None:
        return None
    try:
        if area == AREA_DECK:
            return CARD_DB.get(sel["deck"][index]["id"])
        cur = obs.get("current")
        if not cur:
            return None
        pi = player_index if player_index is not None else cur["yourIndex"]
        p = cur["players"][pi]
        if area == AREA_HAND:
            hand = p.get("hand")
            return CARD_DB.get(hand[index]["id"]) if hand else None
        if area == AREA_DISCARD:
            discard = p.get("discard") or []
            return CARD_DB.get(discard[index]["id"]) if 0 <= index < len(discard) else None
        if area == AREA_BENCH:
            bench = p.get("bench") or []
            return CARD_DB.get(bench[index]["id"]) if 0 <= index < len(bench) else None
    except Exception:
        return None
    return None


def resolve_inplay_id(obs, in_play_index, player_index=None):
    """Card id of the Pokemon at in-play slot `in_play_index` (0=active, 1..5=bench)."""
    cur = obs.get("current")
    if not cur or in_play_index is None:
        return None
    try:
        pi = player_index if player_index is not None else cur["yourIndex"]
        p = cur["players"][pi]
        if in_play_index == 0:
            active = p.get("active") or []
            return active[0]["id"] if active else None
        bench = p.get("bench") or []
        idx = in_play_index - 1
        return bench[idx]["id"] if 0 <= idx < len(bench) else None
    except Exception:
        return None


def get_opponent_active_hp(obs):
    cur = obs.get("current")
    if not cur:
        return None
    try:
        opp = 1 - cur["yourIndex"]
        active = cur["players"][opp].get("active") or []
        return active[0]["hp"] if active else None
    except Exception:
        return None


def apply_weakness_resistance(obs, dmg):
    """Adjust a flat attack-damage number for the real Weakness/Resistance
    rule. Verified empirically against the native engine (a probe pitting a
    known-damage attack against fixed weak-to-Fighting and resistant-to-
    Fighting opponents showed exactly x2 damage on the weakness match and a
    flat -30 on the resistance match, floored at 0) -- this had previously
    been left unimplemented as "unverified" (see docs/ENGINE_NOTES.md).
    attack_score/attack_is_lethal only ever compared the raw `damage` field
    to the opponent's HP, so a hit that's actually lethal thanks to Weakness
    could be scored as merely a setup move, and a hit into a Resistant
    target could be overvalued."""
    if dmg <= 0:
        return dmg
    cur = obs.get("current")
    if not cur:
        return dmg
    try:
        my_active = (cur["players"][cur["yourIndex"]].get("active") or [None])[0]
        my_card = CARD_DB.get(my_active["id"]) if my_active else None
        opp_active = (cur["players"][1 - cur["yourIndex"]].get("active") or [None])[0]
        opp_card = CARD_DB.get(opp_active["id"]) if opp_active else None
        if not my_card or not opp_card:
            return dmg
        my_type = my_card.get("energyType")
        if opp_card.get("weakness") == my_type:
            return dmg * 2
        if opp_card.get("resistance") == my_type:
            return max(0, dmg - 30)
        return dmg
    except Exception:
        return dmg


def card_value(card):
    """Rough heuristic value of a card: bigger/rarer Pokemon and useful
    trainers score higher. Used both to pick the *best* card (search, play,
    evolve target) and, inverted, to pick the *worst* card (discard)."""
    if not card:
        return 0.0
    if card.get("cardType") in (5, 6):  # Basic/Special Energy
        # A real match replay showed a discard choice give up a Snover (a
        # scarce evolution-line piece) to keep a Supporter, while a spare
        # Basic Energy sat in the "keep" pile -- the deck runs 33 copies of
        # it, so any single one is nearly free to discard. Score it clearly
        # below every Pokemon and every other trainer so it's always
        # discarded first when it's an option at all.
        return 2.0
    if card.get("cardType") == 0:  # Pokemon
        val = (card.get("hp") or 0) / 10.0
        if card.get("megaEx"):
            val += 25.0
        elif card.get("ex"):
            val += 15.0
        if card.get("stage2"):
            val += 5.0
        elif card.get("stage1"):
            val += 2.0
        if card.get("name") in OWN_DECK_EVOLUTION_BASES:
            # A raw-HP valuation scores every same-HP Basic identically, so
            # a generically decent Basic (e.g. Farfetch'd) can tie with the
            # one Basic our deck's plan actually depends on (e.g. Riolu),
            # diverting a fraction of limited search/discard decisions away
            # from the card that opens our evolution line. See
            # OWN_DECK_EVOLUTION_BASES's docstring.
            val += 10.0
        return val
    text = " ".join(s.get("text", "") for s in (card.get("skills") or [])).lower()
    val = 6.0
    if card.get("cardType") == 3:  # Supporter
        val += 2.0
    if "search" in text:
        val += 6.0
    if "draw" in text:
        val += 5.0
    if card.get("aceSpec"):
        val += 4.0
    return val


def cheap_reliable_damage(card):
    """Best damage among this Pokemon's low-cost (<=2 energy) attacks.

    Several attacks have a nonzero `damage` field that reads as "free value"
    but is actually conditional and near-always 0 in practice early game
    (e.g. Kyogre's Riptide: "20 damage per Basic Water Energy in your
    discard pile" -- 0 discard early on means 0 damage). Real match replays
    showed our old active-Pokemon choice (highest HP/ex) picking exactly
    such a dead early attacker over a Pokemon with a smaller but *actual*
    guaranteed hit, costing several turns of zero board pressure. This
    proxies for "will the cheapest attack actually do something on turn 1-2"
    by looking only at the flat damage value, which is the one thing we can
    read straight from AllAttack() without parsing effect text.
    """
    if not card or not card.get("attacks"):
        return 0.0
    best = 0.0
    for aid in card["attacks"]:
        atk = ATTACK_DB.get(aid)
        if not atk:
            continue
        cost = len(atk.get("energies") or [])
        if cost <= 2:
            best = max(best, atk.get("damage") or 0)
    return best


_DISCARD_ENERGY_DAMAGE_RE = re.compile(
    r"discard the top (\d+) cards.*?(\d+) damage for each (?:basic )?\{?\w*\}?\s*energy", re.IGNORECASE
)


def _expected_discard_damage(text):
    """Some attacks read `damage: 0` in the raw data but their effect text
    describes a real conditional payoff -- e.g. Mega Abomasnow ex's
    Hammer-lanche ("discard the top 6 cards of your deck, 100 damage for
    each Basic Energy discarded"). A real match replay showed an opponent
    using this exact attack for 300-500 damage per hit every turn while our
    agent never once selected it, since attack_score only ever looked at
    the flat `damage` field. This estimates the payoff from our own deck's
    energy density instead of silently treating it as zero."""
    m = _DISCARD_ENERGY_DAMAGE_RE.search(text or "")
    if not m:
        return 0.0
    n_cards, per_energy = int(m.group(1)), int(m.group(2))
    return n_cards * OWN_DECK_ENERGY_RATIO * per_energy


_DISCARD_PILE_ENERGY_DAMAGE_RE = re.compile(
    r"(\d+) damage for each (?:basic )?\{?\w*\}?\s*energy card in your discard pile", re.IGNORECASE
)


def _discard_pile_damage(obs, text):
    """Kyogre's Riptide ("20 damage for each Basic Water Energy card in
    your discard pile") also reads `damage: 0` in the raw data, but unlike
    Hammer-lanche this scales with a number we can count exactly from
    `obs` right now rather than estimate -- our own discard pile. A real
    match replay showed us using this attack 61 times while still treating
    it as zero-damage in the scoring, missing how much stronger it gets as
    the game goes on and energy piles up in the discard. Returns None (not
    0.0) when the text doesn't match, so callers can fall back to other
    damage-estimation patterns instead of assuming zero."""
    m = _DISCARD_PILE_ENERGY_DAMAGE_RE.search(text or "")
    if not m:
        return None
    per_energy = int(m.group(1))
    cur = obs.get("current")
    if not cur:
        return 0.0
    try:
        p = cur["players"][cur["yourIndex"]]
        discard = p.get("discard") or []
        energy_count = sum(1 for c in discard if CARD_DB.get(c.get("id"), {}).get("cardType") in (5, 6))
        return energy_count * per_energy
    except Exception:
        return 0.0


_COIN_FLIP_BONUS_RE = re.compile(
    r"flip a coin\.\s*if heads,?\s*this attack does (\d+) more damage", re.IGNORECASE
)


def _coin_flip_bonus(text):
    """Some attacks' flat `damage` field is only the guaranteed portion --
    e.g. our own Riolu's Quick Attack ("Flip a coin. If heads, this attack
    does 20 more damage.", `damage: 10`) reads as a flat 10 everywhere in
    this codebase, silently dropping the other half of its real expected
    damage. Returns the expected value of that bonus (half the stated
    amount, since the flip is 50/50) for attack_score's general damage
    estimate -- 0.0 when the text doesn't match.

    Deliberately not used by attack_is_lethal: an earlier version added the
    *full* stated bonus there too ("a coin flip that could end the game is
    worth taking the chance on"), but A/B testing showed that reclassifying
    a 50/50 shot as guaranteed-lethal-tier priority measurably hurt win rate
    (see attack_is_lethal's docstring and STRATEGY_REPORT.md for the
    evidence) -- committing to the gamble apparently costs more in forgone
    guaranteed setup than it wins back in successful coin flips."""
    m = _COIN_FLIP_BONUS_RE.search(text or "")
    if not m:
        return 0.0
    return int(m.group(1)) / 2.0


def attack_score(obs, attack_id):
    atk = ATTACK_DB.get(attack_id)
    dmg = (atk.get("damage") if atk else 0) or 0
    if atk and dmg == 0:
        text = atk.get("text")
        discard_pile_dmg = _discard_pile_damage(obs, text)
        dmg = discard_pile_dmg if discard_pile_dmg is not None else _expected_discard_damage(text)
    if atk:
        dmg += _coin_flip_bonus(atk.get("text"))
    dmg = apply_weakness_resistance(obs, dmg)
    score = 60.0 + dmg / 5.0
    opp_hp = get_opponent_active_hp(obs)
    if opp_hp is not None and opp_hp > 0 and dmg >= opp_hp:
        score += 100.0  # lethal bonus
    return score


def prize_value(card):
    """Prizes awarded to the opponent if this Pokemon is KO'd. Verified
    empirically against the native engine (a probe tracking each player's
    own `prize` list -- 6 face-down slots, one flips to non-null per prize
    taken -- against the identity of whichever opposing Pokemon had just
    been active before the drop): KOing a megaEx Pokemon dropped the
    KO-er's remaining-prize count by exactly 3 every single time (120/120
    sampled events), while KOing a plain non-ex Basic dropped it by exactly
    1 every single time (173/173 sampled events), across 100 real self-play
    games. A separate probe against a plain (non-mega) `ex` Pokemon (Pikachu
    ex, built into an isolated minimal deck since our own deck runs none)
    confirmed a third, distinct value: exactly 2 prizes every time, 48/48
    sampled events -- matching the real paper TCG's "ex = 2 prizes" rule,
    which this engine does *not* apply to `megaEx` (that's 3, not 2). Our
    own deck still has no plain-`ex` Pokemon, so this branch doesn't change
    our own retreat behavior -- it matters once this function is used to
    evaluate the *opponent's* board (e.g. picking a gust/switch target)."""
    if not card:
        return 1
    if card.get("megaEx"):
        return 3
    if card.get("ex"):
        return 2
    return 1


_ATTACKER_HAND_DAMAGE_RE = re.compile(
    r"(\d+) damage counters?.*?for each card in your hand", re.IGNORECASE
)
_DEFENDER_HAND_DAMAGE_RE = re.compile(
    r"(\d+) damage for each card in your opponent.s hand", re.IGNORECASE
)


def _evolutions_by_base_name():
    """Maps a Pokemon's name to the CARD_DB entries of every card that lists
    it as `evolvesFrom` -- i.e. what a given Pokemon could evolve into.
    Built once from the *full* CARD_DB (unlike OWN_DECK_EVOLUTION_BASES,
    which only looks at our own 60 cards) since this is used to reason
    about what the *opponent's* active could evolve into, not ours."""
    table = {}
    for card in CARD_DB.values():
        base = card.get("evolvesFrom")
        if base:
            table.setdefault(base, []).append(card)
    return table


EVOLUTIONS_BY_BASE_NAME = _evolutions_by_base_name()


def _hand_scaling_attack_damage(card, energy_count, attacker_hand_count, defender_hand_count):
    """Best hand-size-scaling damage among `card`'s attacks that are already
    affordable with `energy_count` Energy attached. Factored out of
    opponent_lethal_threat_damage so the same check can be applied both to
    the opponent's current active and (see that function's docstring) to
    its next evolution stage."""
    if not card or not card.get("attacks"):
        return 0.0
    best = 0.0
    for aid in card["attacks"]:
        atk = ATTACK_DB.get(aid)
        if not atk:
            continue
        if energy_count < len(atk.get("energies") or []):
            continue  # not affordable yet -- not a live threat this turn
        text = atk.get("text") or ""
        m = _ATTACKER_HAND_DAMAGE_RE.search(text)
        if m:
            best = max(best, int(m.group(1)) * 10 * attacker_hand_count)
            continue
        m = _DEFENDER_HAND_DAMAGE_RE.search(text)
        if m:
            best = max(best, int(m.group(1)) * defender_hand_count)
    return best


def opponent_lethal_threat_damage(obs):
    """Best damage the opponent's *current active* could already deal to
    our active right now, among attacks that scale with hand size rather
    than a flat number -- a real loss replay (episode 85847458, see
    STRATEGY_REPORT.md) showed our full-HP (340/340) Mega Lucario ex
    one-shot by Alakazam's "Powerful Hand" ("place 2 damage counters on
    your opponent's Active Pokemon for each card in your hand" -- 20 x a
    20-card hand = 400 damage), a threat completely invisible to any
    HP%-threshold retreat check since our active never dropped below 100%
    HP before dying. Also covers the mirror-image pattern ("N damage for
    each card in your opponent's hand", e.g. Mind Ruler/Resentful Refrain)
    which scales with *our own* hand size instead.

    Also checks the opponent's active's *next evolution stage* the same
    way, using the same Energy count -- a second real replay (episode
    #86220242, see STRATEGY_REPORT.md 5.12) showed the exact blind spot
    this leaves open: the opponent evolved Kadabra (no hand-scaling attack)
    into Alakazam (Powerful Hand) and attacked with it all within their own
    single turn, invisible to a check that only looks at the active's
    *current* card. Energy carries over through evolution in this engine
    (confirmed in that same replay), so the Energy gate still applies
    correctly to the not-yet-evolved card. This does add unavoidable false
    positives -- the evolution card might not even be in the opponent's
    hand -- but retreating a turn early is far cheaper than eating a
    same-turn evolve-and-OHKO, so erring toward caution here is the right
    trade, consistent with prize_value's retreat-early bias for costly
    Pokemon (see active_in_danger).

    Deliberately conservative otherwise: only counts an attack already
    affordable *right now* (not "could afford after one more attach"),
    since this is evaluated on our own turn, one attach before their next
    turn actually happens -- a cheap approximation, not a perfect one-ply
    simulation."""
    cur = obs.get("current")
    if not cur:
        return 0.0
    try:
        my_hand_count = cur["players"][cur["yourIndex"]].get("handCount") or 0
        opp = cur["players"][1 - cur["yourIndex"]]
        opp_active = (opp.get("active") or [None])[0]
        if not opp_active:
            return 0.0
        opp_card = CARD_DB.get(opp_active.get("id"))
        if not opp_card:
            return 0.0
        opp_hand_count = opp.get("handCount") or 0
        opp_energy_count = len(opp_active.get("energies") or [])
        best = _hand_scaling_attack_damage(
            opp_card, opp_energy_count, opp_hand_count, my_hand_count
        )
        for evo_card in EVOLUTIONS_BY_BASE_NAME.get(opp_card.get("name"), []):
            best = max(
                best,
                _hand_scaling_attack_damage(
                    evo_card, opp_energy_count, opp_hand_count, my_hand_count
                ),
            )
        return best
    except Exception:
        return 0.0


def active_in_danger(obs):
    """True when our active Pokemon is low enough on HP that losing it this
    exchange is a live risk. The threshold scales with prize_value: losing
    a megaEx active hands the opponent 3 prizes at once (half the game, see
    prize_value) rather than 1, so it is worth retreating to a disposable
    Basic well before it is truly on death's door -- not just under the
    flat 35% that is the right call for a Pokemon that only costs 1 prize.

    Also true regardless of HP% when the opponent's active already has a
    live, affordable hand-size-scaling attack that would be lethal this
    instant (see opponent_lethal_threat_damage) -- a threat no HP%
    threshold can ever catch, since it can one-shot a full-HP Pokemon."""
    cur = obs.get("current")
    if not cur:
        return False
    try:
        p = cur["players"][cur["yourIndex"]]
        active = (p.get("active") or [None])[0]
        if not active:
            return False
        max_hp = active.get("maxHp") or 1
        hp = active.get("hp", max_hp)
        if opponent_lethal_threat_damage(obs) >= hp:
            return True
        ratio = hp / max_hp
        threshold = 0.55 if prize_value(CARD_DB.get(active.get("id"))) >= 3 else 0.35
        return ratio < threshold
    except Exception:
        return False


def retreat_score(obs):
    cur = obs.get("current")
    if not cur:
        return 15.0
    try:
        p = cur["players"][cur["yourIndex"]]
        active = (p.get("active") or [None])[0]
        if not active:
            return 15.0
        bench = p.get("bench") or []
        if active_in_danger(obs) and bench:
            return 45.0  # worth retreating a nearly-dead attacker
        return 5.0
    except Exception:
        return 10.0


def bench_is_thin(obs):
    """True when our bench has 0-1 Pokemon. A KO'd active with no backup on
    the bench is an instant loss, so in this state getting another body onto
    the field outweighs the usual evolve/attach priorities."""
    cur = obs.get("current")
    if not cur:
        return False
    try:
        p = cur["players"][cur["yourIndex"]]
        return len(p.get("bench") or []) <= 1
    except Exception:
        return False


def bench_is_empty(obs):
    """True when our bench has 0 Pokemon -- stricter than `bench_is_thin`.
    A traced real loss showed a search effect (Ultra Ball) fetching a
    *second* copy of our evolution while the bench sat at 0, which is dead
    weight with no Basic in play to evolve it from. Deliberately checked
    separately from `bench_is_thin` (0-1): triggering a Basic-over-evolution
    search preference at bench==1 too (not just 0) measured as a regression
    in A/B testing -- with one backup already down, fetching the evolution
    is still the right call."""
    cur = obs.get("current")
    if not cur:
        return False
    try:
        p = cur["players"][cur["yourIndex"]]
        return len(p.get("bench") or []) == 0
    except Exception:
        return False


def hand_has_pokemon(obs):
    """True when our hand currently holds at least one Basic Pokemon --
    the only kind that can go straight onto an empty bench slot (an
    evolution card in hand needs a Basic already in play first, so it
    doesn't help here). Real replays showed losses where the bench never
    got going because no *playable* Pokemon showed up in hand -- this flags
    that specific dead end so a big-draw Supporter can be prioritized over
    topping off energy instead."""
    cur = obs.get("current")
    if not cur:
        return False
    try:
        p = cur["players"][cur["yourIndex"]]
        hand = p.get("hand") or []
        return any(CARD_DB.get(c.get("id"), {}).get("basic") for c in hand)
    except Exception:
        return False


def opponent_underprepared(obs):
    """True when the opponent's active has no energy attached and their
    bench is empty -- a rough "they haven't set up yet" signal. Worth
    punishing by attacking now rather than spending the turn on our own
    setup, since they can't retaliate hard yet either."""
    cur = obs.get("current")
    if not cur:
        return False
    try:
        opp = cur["players"][1 - cur["yourIndex"]]
        active = (opp.get("active") or [None])[0]
        no_energy = not active or not active.get("energies")
        return no_energy and not (opp.get("bench") or [])
    except Exception:
        return False


def attack_is_lethal(obs, attack_id):
    """True when this attack's damage (after Weakness/Resistance -- see
    apply_weakness_resistance) would KO the opponent's active right now.
    Ending the exchange and banking a prize outranks any setup move, so this
    is checked ahead of every other tier.

    Deliberately flat-damage-only -- does *not* count a coin flip's
    best-case bonus (see _coin_flip_bonus, used by attack_score instead).
    An earlier version of this function used the best-case bonus here too
    ("a coin flip that could end the game is worth taking the chance on"),
    reasoning that with nothing better to do this turn, a 50/50 shot at
    lethal should still outrank setup moves. A/B testing showed this made
    things measurably worse (three 600-game runs, ~48.7% pooled, a small
    but consistent dip) versus a variant that kept attack_score's expected-
    value correction but left this function alone (three 600-game runs,
    ~52.4% pooled, clearly favorable) -- committing to the tier-11 top
    priority on a coin flip that only lands half the time apparently costs
    more in forgone guaranteed setup (energy/evolve) than it wins back in
    successful gambles. See STRATEGY_REPORT.md for the full A/B evidence."""
    atk = ATTACK_DB.get(attack_id)
    dmg = (atk.get("damage") if atk else 0) or 0
    dmg = apply_weakness_resistance(obs, dmg)
    opp_hp = get_opponent_active_hp(obs)
    return opp_hp is not None and opp_hp > 0 and dmg >= opp_hp


# ---------------------------------------------------------------------------
# Option scoring
# ---------------------------------------------------------------------------

def score_option(obs, sel, option):
    """Returns a (tier, tiebreak) tuple; higher sorts first.

    Tiers encode the intended sequencing within a single MAIN-context turn:
    evolve > attach energy > play a card > attack > retreat > pass/end. Other
    contexts (deck search, discard, coin flip, ...) mostly present only one
    option type at a time, so only the tiebreak matters there.

    Several situational overrides bump a tier out of that default order,
    checked roughly in order of urgency:
    - a lethal attack (see `attack_is_lethal`) outranks everything -- there's
      no setup worth doing instead of ending the exchange now.
    - getting a Pokemon onto a too-thin bench, or saving a low-HP active by
      retreating it (see `bench_is_thin` / `active_in_danger`), outranks
      evolve/attach when we're at risk of a Pokemon down with no backup.
    - attacking beats attaching energy once the opponent looks unprepared to
      hit back (see `opponent_underprepared`). (A "we're behind on prizes,
      so attack more" override was tried and measurably made things worse in
      self-play here -- this deck's plan is a slow evolution into a big
      attacker, so being behind means "catch up on energy," not "swing now.")
    - a big-draw Supporter beats attaching energy when the bench is thin and
      no Pokemon is in hand to put on it (see `hand_has_pokemon`) -- digging
      for a body to play is more urgent than energy that has nowhere new to
      go yet.
    - when picking a card from a search effect (Ultra Ball, Brock's
      Scouting, etc.) with the bench completely empty, a Basic Pokemon
      outranks an evolution card (see `bench_is_empty`) -- fetching another
      copy of the evolution is dead weight with no Basic in play to evolve
      it from. Checked against `bench_is_empty` rather than `bench_is_thin`
      deliberately: applying this at bench<=1 too (not just 0) measured as a
      regression in A/B testing.

    A "stop stacking energy on an already-maxed attacker, spread it to the
    bench instead" override was also tried (replays visibly showed a 4th/5th
    energy piling onto one Pokemon). It measurably lowered the win rate over
    300 seeded self-play games despite doing exactly what it was meant to do
    -- this deck's plan lives or dies on getting Mega Abomasnow ex's 3 energy
    together fast, and diverting energy elsewhere delays that more than it
    helps the bench. Removed rather than kept as a known regression.
    """
    t = option.get("type")
    ctx = sel.get("context")

    if t == OPT_END:
        return (0, 0.0)
    if t == OPT_NO:
        return (1, 0.0)
    if t == OPT_NUMBER:
        return (2, float(option.get("number") or 0))
    if t == OPT_RETREAT:
        tier = 8.7 if active_in_danger(obs) else 3
        return (tier, retreat_score(obs))
    if t == OPT_CARD:
        card = resolve_card_by_area(obs, sel, option.get("area"), option.get("index"), option.get("playerIndex"))
        val = card_value(card)
        if bench_is_empty(obs) and card and card.get("cardType") == 0 and card.get("basic"):
            # A traced real loss showed Ultra Ball fetching a *second* Mega
            # Lucario ex while the bench sat at 0 -- useless, since there was
            # no Riolu in play to evolve it from. With an empty bench, a
            # Basic that can go straight onto it now outranks fetching
            # another copy of an evolution we can't play yet.
            val += 100.0
        if ctx == CTX_DISCARD:
            return (4, -val)  # discard the least useful card
        if ctx in (CTX_SETUP_ACTIVE, CTX_TO_ACTIVE):
            # The active slot attacks first and most often, so a Pokemon
            # whose cheap attack is real damage beats one that's merely
            # bigger on paper (see cheap_reliable_damage's docstring).
            return (7, val * 0.5 + cheap_reliable_damage(card) * 1.5)
        return (7, val)  # search / switch-in / reveal: take the best card
    if t == OPT_YES:
        return (5, 1.0)
    if t == OPT_ATTACK:
        if attack_is_lethal(obs, option.get("attackId")):
            tier = 11
        elif opponent_underprepared(obs):
            tier = 8.5
        else:
            tier = 6
        return (tier, attack_score(obs, option.get("attackId")))
    if t in (OPT_PLAY, OPT_ABILITY):
        card = resolve_card_by_area(obs, sel, AREA_HAND, option.get("index"))
        is_bench_pokemon = card and card.get("cardType") == 0
        urgent = is_bench_pokemon and (bench_is_thin(obs) or active_in_danger(obs))
        text = " ".join(s.get("text", "") for s in (card.get("skills") or [])).lower() if card else ""
        # No Pokemon in hand with a thin bench is the exact dead end that
        # cost us games in replay review -- dig for one with a big draw
        # card before spending the turn on energy that won't have anywhere
        # new to go.
        digging = "draw" in text and bench_is_thin(obs) and not hand_has_pokemon(obs)
        tier = 10 if urgent else (8.6 if digging else 7)
        return (tier, card_value(card))
    if t in (OPT_ATTACH, OPT_ENERGY):
        in_play_index = option.get("inPlayIndex", 0)
        base = 40.0 - float(in_play_index)  # prefer active, then low bench slots
        hand_card = resolve_card_by_area(obs, sel, option.get("area", AREA_HAND), option.get("index"))
        target_card = CARD_DB.get(resolve_inplay_id(obs, in_play_index))
        if hand_card and target_card and hand_card.get("energyType") == target_card.get("energyType"):
            base += 5.0
        return (8, base)
    if t == OPT_EVOLVE:
        hand_card = resolve_card_by_area(obs, sel, option.get("area", AREA_HAND), option.get("index"))
        target_card = CARD_DB.get(resolve_inplay_id(obs, option.get("inPlayIndex")))
        gain = card_value(hand_card) - card_value(target_card)
        return (9, 50.0 + gain)
    return (1, 0.0)


def decide(obs):
    sel = obs.get("select")
    if sel is None:
        return load_deck()

    options = sel.get("option") or []
    n = len(options)
    if n == 0:
        return []

    min_c = sel.get("minCount") or 0
    max_c = max(sel.get("maxCount") or 0, min_c)

    scored = sorted(range(n), key=lambda i: score_option(obs, sel, options[i]), reverse=True)

    if max_c <= min_c:
        k = min_c
    else:
        top_tier, _ = score_option(obs, sel, options[scored[0]])
        k = max_c if top_tier >= 5 else min_c  # only "opt in" to optional picks when worthwhile

    k = max(min_c, min(max_c, k, n))
    return scored[:k]


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def _fallback(obs):
    sel = obs.get("select")
    if sel is None:
        return load_deck()
    try:
        n = len(sel.get("option") or [])
        min_c = sel.get("minCount") or 0
        max_c = min(sel.get("maxCount") or 0, n)
        k = min(max(min_c, max_c if max_c >= min_c else min_c), n)
        return list(range(k))
    except Exception:
        return []


def agent(obs):
    try:
        sel = obs.get("select")
        result = decide(obs)

        if sel is None:
            return result if isinstance(result, list) and len(result) == 60 else load_deck()

        n = len(sel.get("option") or [])
        min_c = sel.get("minCount") or 0
        max_c = min(sel.get("maxCount") or 0, n)

        if not isinstance(result, list):
            raise ValueError("agent produced a non-list result")

        seen = set()
        clean = []
        for i in result:
            if isinstance(i, int) and 0 <= i < n and i not in seen:
                seen.add(i)
                clean.append(i)

        if len(clean) < min_c:
            for i in range(n):
                if i not in seen:
                    clean.append(i)
                    seen.add(i)
                if len(clean) >= min_c:
                    break
        if len(clean) > max_c:
            clean = clean[:max_c]
        return clean
    except Exception:
        return _fallback(obs)
